# Generated by Django 3.1.1 on 2020-10-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='notify_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laptop',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
